import test from 'node:test';import assert from 'node:assert/strict';import {extractLearnerProfile,nextProfileQuestion} from './profile.ts';import {verifyCoachAnswer} from './guardrail.ts';
test('profile agent extracts decision constraints',()=>{const p=extractLearnerProfile('I want an online certificate under $20,000 within 2 years near Detroit, MI');assert.equal(p.learningMode,'online');assert.equal(p.credential,'Certificate');assert.equal(p.budget,20000);assert.equal(p.timeline,'2 years');assert.equal(p.location,'Detroit, MI')});
test('profile agent reports information gaps',()=>{const p=extractLearnerProfile('Help me choose');assert.ok(p.missing.includes('budget'));assert.ok(p.missing.includes('credential'))});
test('profile agent preserves earlier constraints across turns',()=>{const first=extractLearnerProfile('online under $20,000');const second=extractLearnerProfile('I want a certificate',first);assert.equal(second.learningMode,'online');assert.equal(second.budget,20000);assert.equal(second.credential,'Certificate')});
test('profile agent asks for the next missing constraint',()=>{const p=extractLearnerProfile('online under $20,000');assert.match(nextProfileQuestion(p),/quickly/) });
test('profile agent understands a timeline written in words',()=>{const p=extractLearnerProfile('I can finish in two years');assert.equal(p.timeline,'two years');assert.doesNotMatch(nextProfileQuestion(p),/quickly/) });
test('guardrail accepts grounded cautious output',()=>assert.equal(verifyCoachAnswer('This broad field shows +6.2% growth; verify program details.',[{field:'Health',jobGrowth:6.2}]).passed,true));
test('guardrail blocks unsupported numbers and guarantees',()=>{const result=verifyCoachAnswer('You have a guaranteed 99% chance.',[{field:'Health',jobGrowth:6.2}]);assert.deepEqual(result.issues,['unsupported_numeric_claim','unsafe_confidence'])});
test('guardrail blocks unsupported program availability claims',()=>{const result=verifyCoachAnswer('This field offers an online program you can finish in two years within your $20,000 budget.',[{field:'Health',jobGrowth:6.2}]);assert.ok(result.issues.includes('unsupported_program_claim'))});
