'use client';
import { useState } from 'react';
type Evidence={field:string;credential?:string;score?:number;jobGrowth?:number|null;annualOpenings?:number|null;programChange?:number|null};type Props={interest:string;workStyle:string;priority:string;evidence:Evidence[]};type Message={role:'coach'|'you';text:string;mode?:string};type Profile={budget:number|null;timeline:string|null;location:string|null;credential:string|null;learningMode:string|null;careerGoal:string|null;missing:string[]};
const starters=['Why is the first field a match?','I need an online program under $20,000 in 2 years.','Help me turn this into an action plan.'];
export default function Coach({interest,workStyle,priority,evidence}:Props){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[loading,setLoading]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[messages,setMessages]=useState<Message[]>([{role:'coach',text:'I can explain these results, surface tradeoffs, and help you plan your next question.'}]);
 const ask=async(text=input)=>{const message=text.trim();if(!message||loading)return;setOpen(true);setInput('');setMessages(current=>[...current,{role:'you',text:message}]);setLoading(true);try{const response=await fetch('/api/coach',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,profile:{interest,workStyle,priority},evidence})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Coach request failed.');setProfile(data.profile||null);setMessages(current=>[...current,{role:'coach',text:`${data.answer}\n\n${data.nextQuestion}`,mode:data.mode}])}catch{setMessages(current=>[...current,{role:'coach',text:'I could not respond just now. Your exploration results still work—please try again.'}])}finally{setLoading(false)}};
 const understood=profile?[profile.credential,profile.learningMode,profile.timeline,profile.location,profile.budget?`Up to ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(profile.budget)}`:null,profile.careerGoal?`Goal: ${profile.careerGoal}`:null].filter(Boolean):[];
 return <section className={`coach ${open?'open':''}`} aria-labelledby="coach-title"><button className="coach-toggle" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span aria-hidden="true">✦</span><span><b id="coach-title">Ask the Viascope Coach</b><small>Grounded in the evidence on this page</small></span><i>{open?'Close':'Open'}</i></button>{open&&<div className="coach-body"><div className="coach-status"><span>Evidence-grounded</span><small>Every generated answer is checked before it is shown.</small></div>{profile&&<div className="coach-profile"><b>What I understood</b>{understood.length?<div>{understood.map(item=><span key={String(item)}>{item}</span>)}</div>:<span>Tell me your budget, timeline, location, credential, or preferred learning format.</span>}<small>Still useful to know: {profile.missing.slice(0,3).join(', ')}.</small></div>}<div className="coach-messages" aria-live="polite">{messages.map((m,i)=><article className={m.role} key={i}><b>{m.role==='coach'?'Coach':'You'}{m.mode?` · ${m.mode==='rules'?'rules mode':'AI-assisted'}`:''}</b><p>{m.text}</p></article>)}{loading&&<p className="coach-thinking">Structuring your priorities and checking the evidence…</p>}</div><div className="coach-starters">{starters.map(s=><button key={s} onClick={()=>ask(s)} disabled={loading}>{s}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask()}}><label className="sr-only" htmlFor="coach-input">Question for the Viascope Coach</label><input id="coach-input" value={input} onChange={e=>setInput(e.target.value)} maxLength={800} placeholder="Try: online, under $20,000, within 2 years…"/><button disabled={loading||!input.trim()}>Ask</button></form><p className="coach-privacy">Only this question, your current interests, and up to five visible field summaries are sent to the coach.</p></div>}</section>;
}
